#!/usr/bin/python3

import sys
import time

def charByChar(text, wait):
    for char in text:
        sys.stdout.write(char)

        sys.stdout.flush()
        time.sleep(wait)

if __name__ == '__main__':
    args = sys.argv[1:]

    if '-h' in args or '--help' in args:
        print('''Print stdin char by char
usage: 
    - by pipe -> some_command | cbc [OPTIONS]
    - by args -> cbc [OPTIONS] [TEXT]

options:
    -t, --time          Sets the time duration of printing, default is 3 seconds
    -i, --interval      Sets the time interval between each character
    -h, --help          Show this message and exit''')
        sys.exit(0)
    
    waitTime = 3 
    interval = 0

    if '-t' in args or '--time' in args:
        try:
            index = args.index('-t')
        except:
            index = args.index('--time')

        try:    
            waitTime = float(args[index+1])
        except:
            print('Time format error')
            sys.exit(1)

        args.pop(index+1)
        args.pop(index)
    
    elif '-i' in args or '--interval' in args:
        try:
            index = args.index('-i')
        except:
            index = args.index('--interval')

        try:    
            interval = float(args[index+1])
        except:
            print('Time format error')
            sys.exit(1)

        args.pop(index+1)
        args.pop(index)

    if sys.stdin.isatty():
        if args:
            text = ' '.join(args)

        else:
            print('No input provided')
            sys.exit(0)
    
    else:
        text = sys.stdin.read()
    
    wait = interval if interval else waitTime / len(text)
    if '-t' in args or '--time' in args:
        wait = float(args[2]) / len(text)
        
    charByChar(text, wait)
    print('')
